#!/usr/bin/env bash
set -euo pipefail

export DRY_RUN=true
export LIVE_TRADING=false
export PUBLIC_MARKET_DRY_RUN=true
export PUBLIC_MARKET_WS_ONLY=true
export ALLOW_CACHED_EXCHANGE_FILTERS_IN_DRY_RUN=true
export CACHED_EXCHANGE_FILTERS_PATH="${CACHED_EXCHANGE_FILTERS_PATH:-./config/exchange_filters_ETHUSDC.json}"
export REQUIRE_REST_EXCHANGE_INFO_FOR_LIVE=true
export REQUIRE_SIGNED_REST_VALIDATION_FOR_TESTNET=true
export TESTNET_ORDER_TEST=false
export BINANCE_SYMBOL=ETHUSDC
export BINANCE_INTERVAL=15m
export BINANCE_ENV="${BINANCE_ENV:-mainnet}"
export BINANCE_API_KEY=
export BINANCE_API_SECRET=
export PUBLIC_MARKET_DRY_RUN_SECONDS="${PUBLIC_MARKET_DRY_RUN_SECONDS:-300}"
export LOG_LEVEL="${LOG_LEVEL:-DEBUG}"

python -m bot.main
